name = "personal-site"
type = "webpack"
route = 'quirl.co.nz/*'
zone_id = '3d836ced4235033ce748de8fd72dab9b'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = ".",entry-point = "workers-site"}
compatibility_date = "2021-10-11"
