name = "personal-site"
route = 'quirl.co.nz/*'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
site = {bucket = "."}
main = "workers-site/index.js"
compatibility_date = "2021-10-11"
