title: Sinkingpoint
email: your-email@domain.com
description: >
  Musings from someone who ought to know better
baseurl: "/blarg"
url: ""
twitter_username: ""
github_username:  sinkingpoint

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
